# Generated by Django 2.1.5 on 2020-07-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_name', models.CharField(max_length=200)),
                ('tutorial_text', models.TextField()),
                ('date published', models.DateField()),
            ],
        ),
    ]
