# Generated by Django 2.1.5 on 2020-07-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200711_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='date published',
            new_name='date_published',
        ),
    ]
